pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "SklearnIntentClassifier"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"

policies:
  - name: MappingPolicy
  - name: MemoizationPolicy
    max_history: 3
  - name: "examples.restaurantbot.policy.RestaurantPolicy"
    batch_size: 100
    epochs: 400
    validation_split: 0.2

language: en
